# Generated by Django 4.2.25 on 2025-11-27 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('cardio', 'Cardio'), ('weights', 'Weightlifting'), ('yoga', 'Yoga'), ('hiit', 'HIIT'), ('pilates', 'Pilates')], default='cardio', help_text='Type of fitness activity for this session', max_length=20)),
                ('date', models.DateField(help_text='Date when this session takes place')),
                ('time', models.TimeField(help_text='Start time for this session')),
                ('capacity', models.IntegerField(default=10, help_text='Maximum number of attendees allowed to book this session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=True, help_text='True if user attended; False if marked as no-show by admin')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session', 'user')},
            },
        ),
        migrations.AddField(
            model_name='session',
            name='attendees',
            field=models.ManyToManyField(blank=True, help_text='Users who have booked a spot in this session', related_name='booked_sessions', through='api.SessionAttendee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='trainer',
            field=models.ForeignKey(help_text='Staff member leading this session', on_delete=django.db.models.deletion.CASCADE, related_name='trainer_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
