# Generated by Django 5.2.8 on 2025-12-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration_minutes',
            field=models.IntegerField(default=60, help_text='Duration of the session in minutes'),
        ),
    ]
