# Generated by Django 4.2.25 on 2025-11-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_session_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='created_by',
        ),
        migrations.AddField(
            model_name='session',
            name='activity_type',
            field=models.CharField(choices=[('cardio', 'Cardio'), ('weights', 'Weightlifting'), ('yoga', 'Yoga'), ('hiit', 'HIIT'), ('pilates', 'Pilates')], default='cardio', max_length=20),
        ),
    ]
