# Generated by Django 4.2.25 on 2025-11-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_session_created_by_session_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
    ]
