# Generated by Django 4.2.25 on 2025-11-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_note_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='title',
        ),
    ]
